-- AlterTable
ALTER TABLE `Frame` MODIFY `matchingCriteria` ENUM('RECEIPTS_XYZ_ALL_TIME_RUNNING', 'COINBASE_ONCHAIN_VERIFICATIONS_COUNTRY', 'COINBASE_ONCHAIN_VERIFICATIONS_ACCOUNT', 'COINBASE_ONCHAIN_VERIFICATIONS_ONE', 'ALL') NOT NULL DEFAULT 'ALL';
