-- AlterTable
ALTER TABLE `Frame` MODIFY `matchingCriteria` ENUM('RECEIPTS_XYZ_ALL_TIME_RUNNING', 'COINBASE_ONCHAIN_VERIFICATIONS', 'COINBASE_ONCHAIN_VERIFICATIONS_ONE', 'ALL') NOT NULL DEFAULT 'ALL';
